version: 2
jobs:
  release:
    docker:
    - image: minamikhail/circle-ci:3.1
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore ./src/MyFabulousStuff.sln
      - run:
          name: Build Solution
          command: dotnet build ./src/MyFabulousStuff.sln
      - run:
          name: Test Solution
          command: dotnet test ./src/MyFabulousStuff.sln
  qa:
    docker:
    - image: minamikhail/circle-ci:3.1
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore ./src/MyFabulousStuff.sln
      - run:
          name: Build Solution
          command: dotnet build ./src/MyFabulousStuff.sln
      - run:
          name: Test Solution
          command: dotnet test ./src/MyFabulousStuff.sln
  dev:
    docker:
    - image: minamikhail/circle-ci:3.1
    working_directory: $CIRCLE_WORKING_DIRECTORY
    steps:
      - checkout
      - run:
          name: Restore Packages
          command: dotnet restore ./src/MyFabulousStuff.sln
      - run:
          name: Build Solution
          command: dotnet build ./src/MyFabulousStuff.sln
      - run:
          name: Test Solution
          command: dotnet test ./src/MyFabulousStuff.sln
workflows:
  version: 2
  build_test_dev:
    jobs:
      - dev
